# Generated by Django 2.2.7 on 2019-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('X', models.DecimalField(decimal_places=17, help_text="Location's Longitude", max_digits=20, null=True)),
                ('Y', models.DecimalField(decimal_places=17, help_text="Location's Latitude", max_digits=20, null=True)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=14, primary_key=True, serialize=False)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=2, null=True)),
                ('Date', models.DateField(help_text='Date', null=True)),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '?')], help_text='Age', max_length=8)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnammon', 'Cinnammon')], help_text='Primary Fur Color', max_length=10, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane')], help_text='Location', max_length=15, null=True)),
                ('Specific_Location', models.CharField(help_text='Specific Location', max_length=50, null=True)),
                ('Running', models.BooleanField(help_text='Running')),
                ('Chasing', models.BooleanField(help_text='Chasing')),
                ('Climbing', models.BooleanField(help_text='Climbing')),
                ('Eating', models.BooleanField(help_text='Eating')),
                ('Foraging', models.BooleanField(help_text='Foraging')),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=100, null=True)),
                ('Kuks', models.BooleanField(help_text='Kuks')),
                ('Quaas', models.BooleanField(help_text='Quaas')),
                ('Moans', models.BooleanField(help_text='Moans')),
                ('Tail_flags', models.BooleanField(help_text='Tail flags')),
                ('Tail_twitches', models.BooleanField(help_text='Tail twitches')),
                ('Approaches', models.BooleanField(help_text='Approaches')),
                ('Indifferent', models.BooleanField(help_text='Indifferent')),
                ('Runs_from', models.BooleanField(help_text='Runs from')),
            ],
        ),
    ]
